% Compute f
for i=1:N
    f(i) = m(i) / dt * ( (x_new(i) - x_old(i)) / dt - u_old(i) ) ...
        - F0(i) * sin( omega(i) * t_new ); %#ok<*SAGROW>
    if i==1
        f(i) = f(i) + (K(i)+K(i+1))*x_new(i) - K(i+1)*x_new(i+1) + ...
            (b(i)+b(i+1))*(x_new(i)-x_old(i))/dt - ...
            b(i+1)*(x_new(i+1)-x_old(i+1))/dt;
    elseif i==N
        f(i) = f(i) + K(i)*x_new(i) - K(i)*x_new(i-1) + ...
            b(i)*(x_new(i)-x_old(i))/dt - ...
            b(i)*(x_new(i-1)-x_old(i-1))/dt;
    else
        f(i) = f(i) + (K(i)+K(i+1))*x_new(i) - K(i)*x_new(i-1) ...
            - K(i+1)*x_new(i+1) + ...
            (b(i)+b(i+1))*(x_new(i)-x_old(i))/dt - ...
            b(i)*(x_new(i-1)-x_old(i-1))/dt - ...
            b(i+1)*(x_new(i+1)-x_old(i+1))/dt;
    end
end
